### ISSUE TITLE
How to document the right magnet side?

### ISSUE THREAD

**Issue by filipecalegario** [probatio/probatio-docs#1]

**Comment by jtragtenberg** [comment]
You suggested using the hall effect sensor. What is the standard polarity of the magnets of the Base relating to the hall effect sensor?

**Comment by jtragtenberg** [comment]
We can make a compass with a cork and one of the magnets, through that we find out which side of that magnet is north and we can label itself and all the other magnets by putting them to attract each together

**Comment by jtragtenberg** [comment]
![compass](https://user-images.githubusercontent.com/5085536/99833661-221b1180-2b41-11eb-9d56-a103cab10f03.gif)

**Comment by jtragtenberg** [comment]
![making the compass](https://user-images.githubusercontent.com/5085536/99833766-4c6ccf00-2b41-11eb-825e-f1a5e50d7e5f.jpg)

**Comment by filipecalegario** [comment]
![Uploading IMG_8894.JPG…]()
