### ISSUE TITLE
Confusion with pdf files inside this repository

### ISSUE THREAD

**Issue by jtragtenberg** [probatio/probatio-docs#4]
I got confused with the architecture and overview files. I believe they would be better organised inside a wiki, rather than a repository for documentation. In the wiki a page could be the architecture, the overview could be in the wiki home... And the readme could explain where I could find what.

**Comment by filipecalegario** [comment]
We created the repository [github.com/probatio/probatio](http://github.com/probatio/probatio) to work as the entry point for the project.
