### ISSUE TITLE
How do I put the dual-piston parts together?

### ISSUE THREAD

**Issue by jtragtenberg** [probatio/probatio-docs#5]
First, what kind of spring should I use? Where do I put the magnet? where do I put the hall effect sensor? Facing which way? What polarity of the magnet is directed to which side? What has to fit perfectly? What I need to use glue? How should I glue it?

**Comment by jtragtenberg** [comment]
I used supports in the cup file and had a hard time to take the support out. There could be an indication of that in the documentation. Which configuration I could and shouldn't use for each print

**Comment by jtragtenberg** [comment]
do i need to sand the borders of the top holes?

**Comment by jtragtenberg** [comment]
Should the hall effect sensor be facing this way? witch the fillets facing up?
![85f71d6e-8cf1-4d8e-802d-844b9ffe9ea7](https://user-images.githubusercontent.com/5085536/83193498-866a9480-a10d-11ea-8ac4-1c497dc5d7b2.jpeg)

**Comment by jtragtenberg** [comment]
What about the magnets? should they fit? it would be interesting if there was a fit here to guarantee a centered and levelled position
![](https://user-images.githubusercontent.com/5085536/83193498-866a9480-a10d-11ea-8ac4-1c497dc5d7b2.jpeg)

**Comment by jtragtenberg** [comment]
What about the magnets? should they fit? it would be interesting if there was a fit here to guarantee a centered and levelled position. 
This hole should fit a magnet perfectly? Should it stay at the bottom of the whole of the surface ?
![4f7007a1-72b3-491c-a721-50579793ff3c](https://user-images.githubusercontent.com/5085536/83193997-4d7eef80-a10e-11ea-9787-4eb05f93242a.jpeg)

**Comment by DocSunset** [comment]
> What about the magnets? should they fit? it would be interesting if there was a fit here to guarantee a centered and levelled position.
> This hole should fit a magnet perfectly? Should it stay at the bottom of the whole of the surface ?

Assuming the magnet is meant to fit perfectly in the hole, centered and flush with the top surface, this is arguably a 3d modelling issue rather than a documentation issue.

**Comment by DocSunset** [comment]
> I used supports in the cup file and had a hard time to take the support out. There could be an indication of that in the documentation. Which configuration I could and shouldn't use for each print

This could also be approached by ensuring the STL files have the part modeled in its printing orientation.

It's a good idea though to include information about whether to use supports etc. with the STLs. Unfortunately I don't know of any cross-printer cross-slicer way of sharing this kind of details. A text file may have to suffice.

**Comment by jtragtenberg** [comment]
Yes, we should change the stls orientation so they are ready to print! And I agree we should think of a way to suggest which ones need supports. Maybe a tag at the end on the file name like probatio_block_top_dual_pistons_cap(use_supports).stl or just a “*”. Not the most elegant solution, a table would also be good but I think the file name communicates faster For someone in the printing labor :)

It would be nice to have a table showing 
- a rendered image of each 3d model in the direction it should be printed, 
- a link to the fusion file, 
- which models should be printed together and a visual representation of how the connect, 
- maybe a picture of it with the sensor used, 
- if it need to be printed with supports

can you think of anything else?

**Comment by jtragtenberg** [comment]
About the piston Magnet fitting I believe there should be a fast way to reparametrize the size of the hole if you could only buy a magnet with different dimensions. For now a fusion 360 file is good enough, but maybe we could design it later in openscad. This would also solve issues with poorly calibrated 3D printers with the right magnet dimensions

**Comment by jtragtenberg** [comment]
I will close this issue here then, since it moved to the appropriate repo
